'core.registers' = 100
'core.parts' = ["core", "sugar","colors","leds","mouse","threads","text","timer","keys","stack","rom"]

'leds.width' = 19
'leds.height' = 19
'leds.size' = 32
'leds.radius' = 15

'colors.data' = [
    "#F5F5F5",
    "#D3D3D3",
    "#808080",
    "#F08080",
    "#FFD700",
    "#00FA9A",
    "#87CEFA",
    "#DDA0DD",
]


# REF: http://www.cs.cornell.edu/andru/xsokoban.html
# REF: http://www.cs.cornell.edu/andru/release/xsokoban-3.3c.tar.gz -> /xsokoban/screens/screen.*

'rom.banks' = [
    # bank 0 -> level 0 
    [
        1,1, # player x,y
        2,   # target score
        # tiles
            5,2, # walls
                5,5, 5,6, 5,7, 5,8, 5,9,
            3,2, # walls
                10,10, 9,10, 8,10,
            2,3, # targets
                3,5,
                3,8,
            2,4, # boxes
                10,5,
                10,8,
            0,0, # end
    ],
    # xsokoban screen 1
    [11,12,6,70,2,4,4,5,4,6,4,7,4,8,4,4,5,8,5,4,6,8,6,2,7,3,7,4,7,8,7,9,7,2,8,9,8,0,9,1,9,2,9,4,9,6,9,7,9,9,9,13,9,14,9,15,9,16,9,17,9,18,9,0,10,4,10,6,10,7,10,9,10,10,10,11,10,12,10,13,10,18,10,0,11,18,11,0,12,1,12,2,12,3,12,4,12,6,12,7,12,8,12,10,12,12,12,13,12,18,12,4,13,10,13,11,13,12,13,13,13,14,13,15,13,16,13,17,13,18,13,4,14,5,14,6,14,7,14,8,14,9,14,10,14,6,4,5,6,7,7,5,8,7,8,2,11,5,11,6,3,16,10,17,10,16,11,17,11,16,12,17,12],
]
